# Generated by Django 3.2.5 on 2021-07-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luna', '0002_alter_usuarios_dni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
